name: rate-your-tasks
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app 
      - ./data:/app/data
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]

volumes:
  sqlite_data:

