x-environment-defaults: &environment-defaults
  DEBUG: "True"
  DB_NAME: "tasks"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "postgres"
  DB_PORT: 5432
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  SECRET_KEY: "secret"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - tasks-network

  tasks-app:
    build:
      context: ./core
    ports:
      - "8000:8000"
    networks:
      - tasks-network
    depends_on:
      - postgres
    environment:
      <<: *environment-defaults
    volumes:
      - static_volume:/app/static
    restart: on-failure:5

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "8080:8080"
    networks:
      - tasks-network
    depends_on:
      - tasks-app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - tasks-network

  celery:
    build: 
      context: ./core
    command: celery -A core worker --loglevel=info
    depends_on:
      - redis
      - postgres
    networks:
      - tasks-network
    environment:
      <<: *environment-defaults

  celery-beat:
    build: 
      context: ./core
    command: celery -A core beat --loglevel=info
    depends_on:
      - redis
      - postgres
    networks:
      - tasks-network
    environment:
      <<: *environment-defaults

volumes:
  pg_data:
  static_volume:

networks:
  tasks-network:
    driver: bridge


